apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kubeq
  name: kubeq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubeq
      name: kubeq
    spec:
      containers:
        - name: kubeq
          image: smo921/kubeq:0.0.1
        - name: kubectl
          image: smo921/kubectl:latest
          args:
            - "proxy"

